### ISSUE TITLE
Add Angry Senpai Icons to the Freeplay Menu and In-Game

### ISSUE THREAD

**Issue by RomaTukalov** [maxxvoiid/util-peaks#11]
### Describe your feature here.

When I'm started to play Senpai's second song "Roses" in the Freeplay Menu, I found out that in this song Angry Senpai Icons is not shown In-Game, only shown Normal Senpai Icons
![AngrySenpaiIconsisnotshowningame](https://github.com/user-attachments/assets/4335f8c3-7802-45d6-bc2f-3f3f3078819e)

### Why should it be added to Util Peaks?

Because, it's really need it.

**Comment by maxxvoiid** [comment]
I will see if I can add it, thanks for letting me know!

**Comment by maxxvoiid** [comment]
Fixed in 2.1c, thanks for reporting!
